version: "3.0"

services:

  gateway:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICE_PATH: "services/api"
      PORT: 3000
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"   
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"

  service:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICE_PATH: "services/greeter"
    depends_on:
      - nats

  nats:
    image: nats

  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=INFO --docker.exposedbydefault=false
    ports:
      - "3000:80"
      - "127.0.0.1:3001:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml